export const NODE_VERSION = 'NODE_VERSION';
export const NODE_PACKAGE_MANAGER = 'NODE_PACKAGE_MANAGER';
export const ENTRYPOINT_DISABLED = 'ENTRYPOINT_DISABLED';
export const NGINX_ENABLED = 'NGINX_ENABLED';
